### ISSUE TITLE
Opaque favicon on mobile

### ISSUE THREAD

**Issue by NotMyFault** [PaperMC/papermc.io#76]
Today I noticed the favicon does not appear transparent on mobile, like you experience it in a browser.
![](https://i.imgur.com/7p0zJkM.png)
Currently experiencing this on my S20 with Chrome (+ Canary) & Vivaldi while using the build in dark mode.

**Comment by zachbr** [comment]
Is this trying to use the apple touch icon instead of the favicons or the web manifest entries for some reason?
https://github.com/PaperMC/papermc.io/blob/aaa6490933f9a4f0a030eed19eed6e3613e67170/src/favicons/apple-touch-icon.png

I believe that's the only icon that doesn't have a transparent backdrop.

**Comment by NotMyFault** [comment]
> Is this trying to use the apple touch icon instead of the favicons or the web manifest entries for some reason?
> https://github.com/PaperMC/papermc.io/blob/aaa6490933f9a4f0a030eed19eed6e3613e67170/src/favicons/apple-touch-icon.png
> 
> I believe that's the only icon that doesn't have a transparent backdrop.

Seems so; quick check with DevTools appears to pick up the file named.
